---
AWSTemplateFormatVersion: '2010-09-09'
Description: Basic EC2 instance with a basic security group
Parameters: {}
Mappings: {}
Resources:
  BasicVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
  BasicVPCSubnet:
    Type: AWS::EC2::Subnet
    DependsOn:
    - BasicVPC
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: { Ref: BasicVPC }
  Ec2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
    - BasicVPCSubnet
    Properties:
      ImageId: ami-91c593a1
      InstanceType: t2.small
      KeyName: advent2014
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet:
        - Fn::GetAtt:
          - InstanceSecurity
          - GroupId
        SubnetId:
          Ref: BasicVPCSubnet
      Tags:
      - Key: Name
        Value: Demo instance
  InstanceSecurity:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow ssh,web,mosh from everywhere
      VpcId: { Ref: BasicVPC }
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 60000
        IpProtocol: udp
        ToPort: 61000
Outputs:
  InstanceDNS:
    Value:
      Fn::GetAtt:
      - Ec2Instance
      - PublicDnsName
